<h1 align=center style="direction: rtl;line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
ماندن یا نماندن؛ مسئله این است!
</font>
</h1>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    توضیحات ابتدایی
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در درسنامه‌های گذشته با حذف مقادیر از داده و مدیریت مقادیر گم‌شده آشنا شدیم. حال در این تمرین قصد داریم با تمرین و کد زدن مهارت خود را به چالش بکشیم! این تمرین در دو بخش آماده شده‌ است: بخش اول به منظور پیش‌پردازش و بخش دوم برای پاسخ‌دهی به تعدادی سوال تحلیلی از داده طراحی شده‌ است.    
    <br>
    فایل 
    <code>migration_rate.csv</code>
    آمار «مهاجرت به» و «مهاجرت از» کشور‌های مختلف را از سال ۱۹۹۰ تا ۲۰۲۰ نشان می‌دهد. هدف این تمرین، تحلیل نرخ مهاجرت تعدادی از کشورهای موجود در این فایل است. در سلول زیر، توضیحات ستون‌های متفاوت این مجموعه‌داده را مشاهده می‌کنید.
</font>
</p>

<div dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<center>

| نام ستون| توضیح ستون|
|:------------------:|:------------------:|
| Country | نام کشور |
| 1990   | در این ستون نرخ مهاجرت هر کشور در سال ۱۹۹۰ آمده‌ است.|
| 1995   |در این ستون نرخ مهاجرت هر کشور در سال ۱۹۹۵ آمده‌ است.|
| 2000   |در این ستون نرخ مهاجرت هر کشور در سال ۲۰۰۰ آمده‌ است.|
| 2005   |در این ستون نرخ مهاجرت هر کشور در سال ۲۰۰۵ آمده‌ است.|
| 2010   |در این ستون نرخ مهاجرت هر کشور در سال ۲۰۱۰ آمده‌ است.|
| 2015   |در این ستون نرخ مهاجرت هر کشور در سال ۲۰۱۵ آمده‌ است.|
| 2020   |در این ستون نرخ مهاجرت هر کشور در سال ۲۰۲۰ آمده‌ است.|

</center>
</font>
</div>


<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    فرمول محاسبه‌ی نرخ مهاجرت
</font>
</h3>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    نرخ مهاجرت حاصل نسبت تفاوت مهاجران به کشور و مهاجران از کشور، به جمعیت کشور در آن سال به ازای هر ۱۰۰۰ نفر است. به فرمول زیر توجه کنید.
    </font>
</p>

##### $$\frac{(\text{migration in} - \text{migration out}) * 1000 }{population}$$

<p dir=rtl style="direction:trl; text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    این فرمول در حل مسئله هیچ تاثیری ندارد، بلکه فقط برای درک بهتر آورده شده‌ است. 
</font>
</p>

In [162]:
import numpy as np
import pandas as pd

In [163]:
# TODO: read csv file in df
df = pd.read_csv("migration_rate.csv")
df

                Country  1990  1995  2000  2005  2010  2015  2020
0         United States   2.7   3.5   6.5   3.7   3.6   3.2   2.9
1                 India   0.0   NaN  -0.1  -0.3  -0.4  -0.4  -0.4
2    Russian Federation   1.2   3.4   3.2   2.5   3.2   2.5   1.3
3               Germany   4.3   6.6   1.8   NaN   0.1   4.8   6.6
4               Algeria  -0.8  -0.9  -1.1  -1.3   NaN  -0.8  -0.2
..                  ...   ...   ...   ...   ...   ...   ...   ...
186                Mali -12.1  -3.8  -2.8  -1.1  -1.4  -3.7  -2.1
187          Costa Rica   1.2   4.2   4.8   2.0   1.4   0.8   0.8
188              Norway   1.8   2.2   2.7   3.0   6.9   8.8   5.3
189          Tajikistan  -1.3   NaN  -7.9  -4.5  -4.1  -3.4  -2.2
190              Angola   3.5   2.2   2.6   2.9   3.3   1.3   0.2

[191 rows x 8 columns]


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بخش اول : پیش‌پردازش
</font>
</h2>

<div dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    پیش از تحلیل باید مقادیر گم‌شده در مجموعه‌داده را مدیریت کنید و برخی از اطلاعات را نیز از بین ببرید.
<br>
در گام پیش‌پردازش به ترتیب مراحل زیر را انجام دهید.
<ul>
    <li>
کشورهایی که نرخ مهاجرت آن‌ها در هر ۷ سال گم‌شده است (برای هیچ سالی نرخ مهاجرت آن‌ها ثبت نشده) را برای همیشه از مجموعه‌داده حذف کنید.
    </li>
    <li>
مقادیر گم‌شده کشور‌هایی که اطلاعات برخی از سال‌ها را از دست داده‌اند را با میانگین آن کشور پر کنید. به‌عنوان مثال اگر نرخ مهاجرت کشوری از سال ۱۹۹۵ تا ۲۰۲۰ به ترتیب 
<code>5.2-</code>
، 
<code>3.4-</code>
، 
<code>0.7-</code>
، 
<code>0.9</code>
، 
<code>1.3</code>
 و 
 <code>2.5</code>
  باشد، نرخ مهاجرت سال ۱۹۹۰ که گم‌شده بود را باید با عدد 
<code>0.76-</code>
   پر کنید.
    </li>
</ul>
    </font>
</div>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
گام اول پیش‌پردازش
</font>
</h3>

<div dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
کشورهایی که نرخ مهاجرت آن‌ها در هر ۷ سال گم‌شده است (برای هیچ سالی نرخ مهاجرت آن‌ها ثبت نشده) را برای همیشه از مجموعه‌داده حذف کنید.
</font>
</div>

In [164]:
df = df.dropna(thresh = 2)
df

                Country  1990  1995  2000  2005  2010  2015  2020
0         United States   2.7   3.5   6.5   3.7   3.6   3.2   2.9
1                 India   0.0   NaN  -0.1  -0.3  -0.4  -0.4  -0.4
2    Russian Federation   1.2   3.4   3.2   2.5   3.2   2.5   1.3
3               Germany   4.3   6.6   1.8   NaN   0.1   4.8   6.6
4               Algeria  -0.8  -0.9  -1.1  -1.3   NaN  -0.8  -0.2
..                  ...   ...   ...   ...   ...   ...   ...   ...
186                Mali -12.1  -3.8  -2.8  -1.1  -1.4  -3.7  -2.1
187          Costa Rica   1.2   4.2   4.8   2.0   1.4   0.8   0.8
188              Norway   1.8   2.2   2.7   3.0   6.9   8.8   5.3
189          Tajikistan  -1.3   NaN  -7.9  -4.5  -4.1  -3.4  -2.2
190              Angola   3.5   2.2   2.6   2.9   3.3   1.3   0.2

[185 rows x 8 columns]

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
گام دوم پیش‌پردازش
</font>
</h3>

<div dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
مقادیر گم‌شده کشور‌هایی که اطلاعات برخی از سال‌ها را از دست داده‌اند را با میانگین آن کشور پر کنید. به‌عنوان مثال اگر نرخ مهاجرت کشوری از سال ۱۹۹۵ تا ۲۰۲۰ به ترتیب 5.2-، 3.4-، 0.7-، 0.9، 1.3 و 2.5 باشد، نرخ مهاجرت سال ۱۹۹۰ که گم‌شده بود را باید با عدد 0.76- پر کنید.
</font>
</div>

In [165]:
#df = df.fillna(df.mean(numeric_only=True))
#df
df = df.T.fillna(df.mean(axis=1,numeric_only=True)).T
df

                Country  1990      1995 2000      2005  2010 2015 2020
0         United States   2.7       3.5  6.5       3.7   3.6  3.2  2.9
1                 India   0.0 -0.266667 -0.1      -0.3  -0.4 -0.4 -0.4
2    Russian Federation   1.2       3.4  3.2       2.5   3.2  2.5  1.3
3               Germany   4.3       6.6  1.8  4.033333   0.1  4.8  6.6
4               Algeria  -0.8      -0.9 -1.1      -1.3 -0.85 -0.8 -0.2
..                  ...   ...       ...  ...       ...   ...  ...  ...
186                Mali -12.1      -3.8 -2.8      -1.1  -1.4 -3.7 -2.1
187          Costa Rica   1.2       4.2  4.8       2.0   1.4  0.8  0.8
188              Norway   1.8       2.2  2.7       3.0   6.9  8.8  5.3
189          Tajikistan  -1.3      -3.9 -7.9      -4.5  -4.1 -3.4 -2.2
190              Angola   3.5       2.2  2.6       2.9   3.3  1.3  0.2

[185 rows x 8 columns]

<div dir=rtl id="start" style="direction:rtl;text-align: justify;line-height:200%;">
	<font face="vazir" size=3>
        بعد از اتمام هر دو مرحله‌ی پیش‌پردازش، تعداد مقادیر گم‌شده همه‌ی ستون‌ها باید 0 باشد.
    </font>
</div>

In [166]:
df.isna().sum()

Country    0
1990       0
1995       0
2000       0
2005       0
2010       0
2015       0
2020       0
dtype: int64

<div dir=rtl id="start" style="direction:rtl;text-align: justify;line-height:200%;">
	<font face="vazir" size=3>
        <span color=”purple”><b>توجه: </b></span> 
        متغیر <code>df</code> مورد داوری قرار خواهد گرفت، بنابراین به‌غیر از دو گام پیش‌پردازشی، هیچ‌گونه تغییری روی آن اعمال نکنید!
    </font>
</div>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
بخش دوم : تحلیل
</font>
</h2>

<div dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
پس از اینکه دو مرحله‌ی بالا را انجام دادید به سوالات زیر پاسخ دهید.
    <br>
    قصد داریم با پاسخ به سوالات زیر، شهود دقیقی نسبت به وضع مهاجرت در برخی کشور‌ها به‌دست آوریم.
</font>
</div>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
سوال اول
</font>
</h3>

<div dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در سال ۲۰۲۰، <b>اسم</b> سه کشوری که بیشترین نرخ پذیرش مهاجر را دارند پیدا کنید. جواب خود را درون لیست <code>top_countries</code> ذخیره کنید. عنصر اول، دوم و سوم این لیست به ترتیب کشورهایی هستند که در رتبه‌ی اول تا سوم جذب مهاجر قرار می‌گیرند.
</font>
</div>

In [167]:
series_of_maximum = df.set_index('Country').sort_values(by='2020',ascending=False).head(3).index
top_countries = [series_of_maximum[0],series_of_maximum[1],series_of_maximum[2]]
print(top_countries)

['Bahrain', 'Maldives', 'Oman']

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
سوال دوم
</font>
</h3>

<div dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    میانگین نرخ مهاجرت کشور ایران در این بازه‌ی ۳۰ ساله را محاسبه کرده و جواب را در متغیر <code>iran_mean</code> بنویسید. جنس این متغیر باید <code>numpy.float64</code> باشد.
    <br>
    اسم کشور ایران در این مجموعه‌داده به صورت <code>Iran (Islamic Republic of)</code> آمده‌ است.
</font>
</div>

In [168]:
iran_mean = df.loc[df['Country'] == 'Iran (Islamic Republic of)', '1990':'2020'].mean(axis =1).values[0]
print(iran_mean)

-0.22857142857142865

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
سوال سوم
</font>
</h3>

<div dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    <b>اسم</b> کشوری که در این بازه‌ی ۳۰ ساله، بیشترین رشد را داشته است در متغیر <code>highest_growth</code> بنویسید. این متغیر از نوع <i>str</i> است. منظور از رشد، تفاضل نرخ سال ۲۰۲۰ از سال ۱۹۹۰ است.

</font>
</div>

In [169]:
#df['growth_rate'] = df['2020']-df['1990']
#highest_growth = df.set_index('Country').sort_values(by='growth_rate',ascending=False).head(1)
#highest_growth

df['growth_rate'] = df['2020']-df['1990']
highest_growth = df.loc[df['growth_rate'].idxmax()]['Country']
df.drop(columns='growth_rate',inplace=True)
print(highest_growth)

Liberia

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [170]:
# DO NOT CHANGE THIS CELL !
import zipfile
import joblib

df.to_csv('./df.csv', index=False)
joblib.dump(top_countries,"top_countries")
joblib.dump(iran_mean,"iran_mean")
joblib.dump(highest_growth, "highest_growth")


def compress(file_names):
    print("File Paths:")
    print(file_names)
    # Select the compression mode ZIP_DEFLATED for compression
    # or zipfile.ZIP_STORED to just store the file
    compression = zipfile.ZIP_DEFLATED
    # create the zip file first parameter path/name, second mode
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            # Add file to the zip file
            # first parameter file to zip, second filename in zip
            zf.write('./' + file_name, file_name, compress_type=compression)


file_names = ["df.csv", "top_countries", "iran_mean", "highest_growth", "to_stay_or_not_to_stay.ipynb"]
compress(file_names)

File Paths:
['df.csv', 'top_countries', 'iran_mean', 'highest_growth', 'to_stay_or_not_to_stay.ipynb']